spring.application.name=financeiro-api

# Conexão com o Postgres via Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/financeiro
spring.datasource.username=financeiro_user
spring.datasource.password=financeiro_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# A partir de agora, quem cria/altera tabelas é o Flyway, não o Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration