spring.application.name=financeiro-api

spring.datasource.url=jdbc:h2:mem:financeiro
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=userdbtest
spring.datasource.password=senhadbtest

# Console web do H2 (pra você ver as tabelas no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Deixa o Hibernate criar/atualizar as tabelas automaticamente (só nesta fase de aprendizado)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true